export const services = [{
        id: 0,
        title: "наші послуги",
        bgImg: require("@/assets/1.jpg"),
        bgImgBack: require("@/assets/all.jpg"),
        service1: "на нашій території Ви можете отримати весь спектр послуг для здоров'я і краси.       ",
        service2: "Ласкаво просимо на YUG!",
        service3: "",
        service4: "",
        service5: "",
    },

    {
        id: 1,
        title: "перукарське містецтво",
        bgImg: require("@/assets/volos.jpg"),
        bgImgBack: require("@/assets/3.jpg"),
        service1: "стрижки",
        service2: "укладання",
        service3: "фарбування",
        service4: "відновлення волосся",
        service5: "нарощування",
    },

    {
        id: 2,
        title: "косметологія",
        bgImg: require("@/assets/kosmetologia.jpg"),
        bgImgBack: require("@/assets/3.jpg"),
        service1: "чистка обличчя",
        service2: "доглядові процедури",
        service3: "фотоомолодження",
        service4: "карбоксітерапія",
        service5: "карбоновий пілінг",
    },

    {
        id: 3,
        title: "ручки",
        bgImg: require("@/assets/manikur.jpg"),
        bgImgBack: require("@/assets/3.jpg"),
        service1: "Покриття гель-лак",
        service2: "Нарощування нігтів",
        service3: "парафінотерапія",
        service4: "корекція нігтів",
        service5: "Манікюр",
    },

    {
        id: 4,
        title: "ніжки",
        bgImg: require("@/assets/pedikur.jpg"),
        bgImgBack: require("@/assets/3.jpg"),
        service1: "Покриття гель-лак",
        service2: "корекція нігтів",
        service3: "SPA догляд",
        service4: "парафінотерапія",
        service5: "педікюр",
    },

    {
        id: 5,
        title: "тіло",
        bgImg: require("@/assets/massag.jpg"),
        bgImgBack: require("@/assets/3.jpg"),
        service1: "усі види масажу",
        service2: "коррекція фігури",
        service3: "SPA догляд",
        service4: "Скрабування, ",
        service5: " зволоження",
        service6: " та Обгортання ",
        service7: "  за типом шкіри",
    },

    {
        id: 6,
        title: "татуаж",
        bgImg: require("@/assets/tatuag.jpg"),
        bgImgBack: require("@/assets/3.jpg"),
        service1: "ТАТУАЖ БРІВ",
        service2: "ПУДРОВІ БРОВИ",
        service3: "МІКРОБЛЕЙДИНГ БРІВ",
        service4: "МІКРОБЛЕЙДИНГ БРІВ ",
        service5: "ТАТУАЖ ПОВІК",
    },

    {
        id: 7,
        title: "вії",
        bgImg: require("@/assets/brovi.jpg"),
        bgImgBack: require("@/assets/3.jpg"),
        service1: "Класичне ",
        service2: "нарощування вій",
        service3: "2D, 3D ",
        service4: "нарощування вій",
        service5: "ламінування",
    },

    {
        id: 8,
        title: "депіляція",
        bgImg: require("@/assets/depilacia.jpg"),
        bgImgBack: require("@/assets/3.jpg"),
        service1: "шугарінг",
        service2: "воскова епіляція",
        service3: "лазерна депіляція",
        service4: "",
        service5: "",
    },

]

export const reviews = [{
        id: 1,
        userName: 'Світлана',
        userImg: require("@/assets/cli1.jpg"),
        text: 'Хороший сервіс, прекрасні майстри, мені все сподобалося, дуже рекомендую',
    },
    {
        id: 2,
        userName: 'Юлія',
        userImg: require("@/assets/cli2.jpg"),
        text: 'Неймовірно красивий салон, шикарна атмосфера, все дуже стильно і мило. Відмінний сервіс, круті майстри, дуже ввічливий персонал. Цей салон став для мене відкриттям.',
    },
    {
        id: 3,
        userName: 'Олена',
        userImg: require("@/assets/cli4.jpg"),
        text: 'У мене залишилися тільки позитивні емоції. Обслуговування було на хорошому рівні. Я всім задоволена',
    },
    {
        id: 4,
        userName: 'Ольга',
        userImg: require("@/assets/cli3.jpg"),
        text: "Стильний інтер'єр, приємний персонал. Дуже сподобалась робота майстра Тетяни. Дуже уважно, професійно, добрий догляд! Спасибі, все супер!",
    },
    {
        id: 5,
        userName: 'Антоніна',
        userImg: require("@/assets/cli5.jpg"),
        text: 'В салоні працює відмінна команда: увагу, настрій і задоволення від результату гарантовано!',
    },
]